// healthcare-backend/src/constants/roles.js
/**
 * 🏥 HỆ THỐNG PHÂN QUYỀN RBAC CHO ỨNG DỤNG Y TẾ
 * Tác giả: Healthcare Development Team
 * Phiên bản: 2.0 - Đã refine bảo mật & thực tế hơn (22/12/2025)
 * 
 * Các thay đổi chính so với bản gốc:
 * - HOSPITAL_ADMIN không được tạo HOSPITAL_ADMIN khác (chỉ SUPER_ADMIN mới được)
 * - Thêm PATIENT.UPDATE_ADMINISTRATIVE cho lễ tân cập nhật thông tin hành chính
 * - DEPARTMENT_HEAD được register DOCTOR và NURSE trong khoa
 * - Tách rõ APPOINTMENT.REQUEST_CANCEL (chỉ bệnh nhân) và CONFIRM_CANCEL
 * - CLINICAL_ADMIN có thêm quyền register bác sĩ cao cấp
 * - Cải thiện comment và cấu trúc
 */

const ROLES = Object.freeze({
  // ===== QUẢN TRỊ HỆ THỐNG =====
  SUPER_ADMIN: 'SUPER_ADMIN',         // Quyền cao nhất (dev ops)
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',       // Quản trị hệ thống (không liên quan y tế)
  CLINICAL_ADMIN: 'CLINICAL_ADMIN',   // Bác sĩ trưởng cao cấp

  // ===== QUẢN TRỊ BỆNH VIỆN & KHOA =====
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',   // Quản trị viên bệnh viện
  DEPARTMENT_HEAD: 'DEPARTMENT_HEAD', // Trưởng khoa/phòng

  // ===== NHÂN VIÊN Y TẾ =====
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',

  // ===== NHÂN VIÊN HÀNH CHÍNH =====
  RECEPTIONIST: 'RECEPTIONIST',
  BILLING_STAFF: 'BILLING_STAFF',

  // ===== NGƯỜI DÙNG BÊN NGOÀI =====
  PATIENT: 'PATIENT',
  GUEST: 'GUEST',
});

// ===== DANH SÁCH QUYỀN (PERMISSIONS) =====
const PERMISSIONS = Object.freeze({
  // Đăng nhập / Đăng ký
  'AUTH_LOGIN': 'AUTH.LOGIN',
  'AUTH_LOGOUT': 'AUTH.LOGOUT',
  'AUTH_SELF_REGISTER': 'AUTH.SELF_REGISTER',

  // Đăng ký người dùng (chỉ cấp cho vai trò cao)
  'AUTH_REGISTER_PATIENT': 'AUTH.REGISTER_PATIENT',
  'AUTH_REGISTER_RECEPTIONIST': 'AUTH.REGISTER_RECEPTIONIST',
  'AUTH_REGISTER_BILLING_STAFF': 'AUTH.REGISTER_BILLING_STAFF',
  'AUTH_REGISTER_LAB_TECHNICIAN': 'AUTH.REGISTER_LAB_TECHNICIAN',
  'AUTH_REGISTER_PHARMACIST': 'AUTH.REGISTER_PHARMACIST',
  'AUTH_REGISTER_NURSE': 'AUTH.REGISTER_NURSE',
  'AUTH_REGISTER_DOCTOR': 'AUTH.REGISTER_DOCTOR',
  'AUTH_REGISTER_DEPARTMENT_HEAD': 'AUTH.REGISTER_DEPARTMENT_HEAD',
  'AUTH_REGISTER_HOSPITAL_ADMIN': 'AUTH.REGISTER_HOSPITAL_ADMIN', // Chỉ SUPER_ADMIN

  // Quản lý người dùng
  'USER_VIEW': 'USER.VIEW',
  'USER_CREATE': 'USER.CREATE',
  'USER_UPDATE': 'USER.UPDATE',
  'USER_DELETE': 'USER.DELETE',
  'USER_DISABLE': 'USER.DISABLE', // Fixed: should be dot, matches usage in routes
  'USER_ENABLE': 'USER.ENABLE',
  'USER_RESTORE': 'USER.RESTORE',
  'USER_ASSIGN_DEPARTMENT': 'USER.ASSIGN_DEPARTMENT',
  'USER_VIEW_SENSITIVE': 'USER.VIEW_SENSITIVE',

  // Quản lý bệnh nhân
  'PATIENT_VIEW': 'PATIENT.VIEW',
  'PATIENT_CREATE': 'PATIENT.CREATE',
  'PATIENT_UPDATE': 'PATIENT.UPDATE', // Update y tế (bác sĩ)
  'PATIENT_UPDATE_ADMINISTRATIVE': 'PATIENT.UPDATE_ADMINISTRATIVE', // Update hành chính (lễ tân)
  'PATIENT_DELETE': 'PATIENT.DELETE',
  'PATIENT_ADMIT': 'PATIENT.ADMIT',
  'PATIENT_DISCHARGE': 'PATIENT.DISCHARGE',
  'PATIENT_VIEW_SENSITIVE': 'PATIENT.VIEW_SENSITIVE',

  // Hồ sơ bệnh án
  'MEDICAL_VIEW_RECORDS': 'MEDICAL.VIEW_RECORDS',
  'MEDICAL_CREATE_RECORDS': 'MEDICAL.CREATE_RECORDS',
  'MEDICAL_UPDATE_RECORDS': 'MEDICAL.UPDATE_RECORDS',
  'MEDICAL_EXPORT_RECORDS': 'MEDICAL.EXPORT_RECORDS',

  // Tư vấn / Khám bệnh
  'CONSULTATION_VIEW': 'CONSULTATION.VIEW',
  'CONSULTATION_CREATE': 'CONSULTATION.CREATE',
  'CONSULTATION_UPDATE': 'CONSULTATION.UPDATE',

  // Chẩn đoán
  'DIAGNOSIS_VIEW': 'DIAGNOSIS.VIEW',
  'DIAGNOSIS_CREATE': 'DIAGNOSIS.CREATE',
  'DIAGNOSIS_UPDATE': 'DIAGNOSIS.UPDATE',

  // Kế hoạch điều trị
  'TREATMENT_VIEW_PLANS': 'TREATMENT.VIEW_PLANS',
  'TREATMENT_CREATE_PLANS': 'TREATMENT.CREATE_PLANS',
  'TREATMENT_UPDATE_PLANS': 'TREATMENT.UPDATE_PLANS',

  // Đơn thuốc
  'PRESCRIPTION_VIEW': 'PRESCRIPTION.VIEW',
  'PRESCRIPTION_CREATE': 'PRESCRIPTION.CREATE',
  'PRESCRIPTION_UPDATE_DRAFT': 'PRESCRIPTION.UPDATE_DRAFT',
  'PRESCRIPTION_APPROVE': 'PRESCRIPTION.APPROVE',
  'PRESCRIPTION_CANCEL': 'PRESCRIPTION.CANCEL',
  'PRESCRIPTION_DISPENSE': 'PRESCRIPTION.DISPENSE',

  // Lịch hẹn
  'APPOINTMENT_VIEW': 'APPOINTMENT.VIEW',
  'APPOINTMENT_CREATE': 'APPOINTMENT.CREATE',
  'APPOINTMENT_UPDATE': 'APPOINTMENT.UPDATE',
  'APPOINTMENT_REQUEST_CANCEL': 'APPOINTMENT.REQUEST_CANCEL',   // Bệnh nhân yêu cầu hủy
  'APPOINTMENT_CONFIRM_CANCEL': 'APPOINTMENT.CONFIRM_CANCEL',   // Nhân viên duyệt hủy

  // Hàng đợi
  'QUEUE_VIEW': 'QUEUE.VIEW',
  'QUEUE_ADD': 'QUEUE.ADD',
  'QUEUE_WALK_IN': 'QUEUE.WALK_IN',
  'QUEUE_CALL_NEXT': 'QUEUE.CALL_NEXT',
  'QUEUE_SKIP': 'QUEUE.SKIP',
  'QUEUE_RECALL': 'QUEUE.RECALL',
  'QUEUE_COMPLETE': 'QUEUE.COMPLETE',
  'QUEUE_STATS': 'QUEUE.STATS',
  'QUEUE_WAIT_TIME': 'QUEUE.WAIT_TIME',

  // Xét nghiệm
  'LAB_VIEW_ORDERS': 'LAB.VIEW_ORDERS',
  'LAB_CREATE_ORDERS': 'LAB.CREATE_ORDERS',
  'LAB_UPDATE_ORDERS': 'LAB.UPDATE_ORDERS',
  'LAB_VIEW_RESULTS': 'LAB.VIEW_RESULTS',
  'LAB_CREATE_RESULTS': 'LAB.CREATE_RESULTS',
  'LAB_UPDATE_RESULTS': 'LAB.UPDATE_RESULTS',
  'LAB_APPROVE_RESULTS': 'LAB.APPROVE_RESULTS',

  // Hóa đơn / Thanh toán
  'BILL_VIEW': 'BILL.VIEW',
  'BILL_CREATE': 'BILL.CREATE',
  'BILL_UPDATE': 'BILL.UPDATE',
  'BILL_PROCESS_PAYMENTS': 'BILL.PROCESS_PAYMENTS',
  'BILL_APPROVE_REFUND': 'BILL.APPROVE_REFUND',
  'BILL_VIEW_REPORTS': 'BILL.VIEW_REPORTS',

  // Quản lý kho
  'INVENTORY_VIEW': 'INVENTORY.VIEW',
  'INVENTORY_UPDATE': 'INVENTORY.UPDATE',
  'INVENTORY_MANAGE_MEDICATION': 'INVENTORY.MANAGE_MEDICATION',
  'INVENTORY_CREATE': 'INVENTORY.CREATE',
  'INVENTORY_ADJUST': 'INVENTORY.ADJUST',
  'INVENTORY_ALERTS': 'INVENTORY.ALERTS',

  // Quản lý giường bệnh
  'BED_VIEW': 'BED.VIEW',
  'BED_UPDATE': 'BED.UPDATE',
  'BED_ASSIGN': 'BED.ASSIGN',
  'BED_TRANSFER': 'BED.TRANSFER',
  'BED_DISCHARGE': 'BED.DISCHARGE',
  'BED_MANAGE': 'BED.MANAGE',
  'BED_VIEW_STATS': 'BED.VIEW_STATS',

  // Thông báo nội bộ
  'NOTIFICATION_VIEW': 'NOTIFICATION.VIEW',
  'NOTIFICATION_SEND': 'NOTIFICATION.SEND',
  'NOTIFICATION_SYSTEM': 'NOTIFICATION.SYSTEM',

  // Báo cáo
  'REPORT_VIEW': 'REPORT.VIEW',
  'REPORT_GENERATE': 'REPORT.GENERATE',
  'REPORT_EXPORT': 'REPORT.EXPORT',

  // Khẩn cấp & Hệ thống
  'EMERGENCY_ACCESS': 'EMERGENCY.ACCESS',
  'SYSTEM_CONFIG': 'SYSTEM.CONFIG',
  'SYSTEM_VIEW_AUDIT_LOG': 'SYSTEM.VIEW_AUDIT_LOG',
  'SYSTEM_BACKUP_DATA': 'SYSTEM.BACKUP_DATA',

  // Dịch vụ & Khoa
  'DEPARTMENT_VIEW': 'DEPARTMENT.VIEW',
  'DEPARTMENT_CREATE': 'DEPARTMENT.CREATE',
  'DEPARTMENT_UPDATE': 'DEPARTMENT.UPDATE',
  'DEPARTMENT_DELETE': 'DEPARTMENT.DELETE',
  'DEPARTMENT_MANAGE': 'DEPARTMENT.MANAGE',
  'SERVICE_VIEW': 'SERVICE.VIEW',
  'SERVICE_MANAGE': 'SERVICE.MANAGE',

  // Lịch làm việc bác sĩ
  'SCHEDULE_VIEW': 'SCHEDULE.VIEW',
  'SCHEDULE_CREATE': 'SCHEDULE.CREATE',
  'SCHEDULE_UPDATE': 'SCHEDULE.UPDATE',
  'SCHEDULE_DELETE': 'SCHEDULE.DELETE',
  'SCHEDULE_MANAGE': 'SCHEDULE.MANAGE'
}); // ← ĐÃ SỬA: Đóng object PERMISSIONS đúng cách

// ===== PHÂN QUYỀN THEO TỪNG VAI TRÒ =====
const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: [...Object.values(PERMISSIONS)], // Toàn quyền

  [ROLES.SYSTEM_ADMIN]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DISABLE, PERMISSIONS.USER_ENABLE, PERMISSIONS.USER_RESTORE,
    PERMISSIONS.USER_ASSIGN_DEPARTMENT,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.SYSTEM_CONFIG, PERMISSIONS.SYSTEM_VIEW_AUDIT_LOG,
    PERMISSIONS.SYSTEM_BACKUP_DATA,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_ALERTS,
    PERMISSIONS.NOTIFICATION_VIEW, PERMISSIONS.NOTIFICATION_SEND, PERMISSIONS.NOTIFICATION_SYSTEM,
  ],

  [ROLES.CLINICAL_ADMIN]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.AUTH_REGISTER_DOCTOR, PERMISSIONS.AUTH_REGISTER_DEPARTMENT_HEAD,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_VIEW_SENSITIVE,
    PERMISSIONS.MEDICAL_VIEW_RECORDS, PERMISSIONS.MEDICAL_EXPORT_RECORDS,
    PERMISSIONS.CONSULTATION_VIEW, PERMISSIONS.CONSULTATION_CREATE, PERMISSIONS.CONSULTATION_UPDATE,
    PERMISSIONS.DIAGNOSIS_VIEW, PERMISSIONS.DIAGNOSIS_CREATE, PERMISSIONS.DIAGNOSIS_UPDATE,
    PERMISSIONS.PRESCRIPTION_VIEW, PERMISSIONS.PRESCRIPTION_APPROVE,
    PERMISSIONS.LAB_VIEW_RESULTS, PERMISSIONS.LAB_APPROVE_RESULTS,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_VIEW_STATS,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_GENERATE, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.EMERGENCY_ACCESS,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_STATS,
  ],

  [ROLES.HOSPITAL_ADMIN]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DISABLE, PERMISSIONS.USER_ENABLE, PERMISSIONS.USER_RESTORE,
    PERMISSIONS.USER_ASSIGN_DEPARTMENT,
    PERMISSIONS.AUTH_REGISTER_PATIENT, PERMISSIONS.AUTH_REGISTER_RECEPTIONIST,
    PERMISSIONS.AUTH_REGISTER_BILLING_STAFF, PERMISSIONS.AUTH_REGISTER_LAB_TECHNICIAN,
    PERMISSIONS.AUTH_REGISTER_PHARMACIST, PERMISSIONS.AUTH_REGISTER_NURSE,
    PERMISSIONS.AUTH_REGISTER_DOCTOR, PERMISSIONS.AUTH_REGISTER_DEPARTMENT_HEAD,
    // Không có AUTH.REGISTER_HOSPITAL_ADMIN → bảo mật
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE, PERMISSIONS.PATIENT_UPDATE_ADMINISTRATIVE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_DISCHARGE,
    PERMISSIONS.MEDICAL_VIEW_RECORDS, PERMISSIONS.MEDICAL_EXPORT_RECORDS,
    PERMISSIONS.CONSULTATION_VIEW, PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_CONFIRM_CANCEL,
    PERMISSIONS.LAB_VIEW_ORDERS, PERMISSIONS.LAB_VIEW_RESULTS,
    PERMISSIONS.BILL_VIEW, PERMISSIONS.BILL_CREATE, PERMISSIONS.BILL_PROCESS_PAYMENTS,
    PERMISSIONS.BILL_APPROVE_REFUND,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_GENERATE, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_ALERTS,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_ASSIGN, PERMISSIONS.BED_TRANSFER,
    PERMISSIONS.BED_DISCHARGE, PERMISSIONS.BED_MANAGE, PERMISSIONS.BED_VIEW_STATS,
    PERMISSIONS.NOTIFICATION_VIEW, PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_STATS, PERMISSIONS.QUEUE_WAIT_TIME,
    PERMISSIONS.EMERGENCY_ACCESS,
    PERMISSIONS.SYSTEM_VIEW_AUDIT_LOG,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_MANAGE,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_CREATE,
    PERMISSIONS.SCHEDULE_UPDATE,
    PERMISSIONS.SCHEDULE_DELETE,
    PERMISSIONS.SCHEDULE_MANAGE,
  ],

  [ROLES.DEPARTMENT_HEAD]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.AUTH_REGISTER_DOCTOR, PERMISSIONS.AUTH_REGISTER_NURSE,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE, PERMISSIONS.PATIENT_UPDATE_ADMINISTRATIVE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_DISCHARGE,
    PERMISSIONS.MEDICAL_VIEW_RECORDS, PERMISSIONS.MEDICAL_CREATE_RECORDS,
    PERMISSIONS.MEDICAL_UPDATE_RECORDS, PERMISSIONS.MEDICAL_EXPORT_RECORDS,
    PERMISSIONS.CONSULTATION_VIEW, PERMISSIONS.CONSULTATION_CREATE, PERMISSIONS.CONSULTATION_UPDATE,
    PERMISSIONS.DIAGNOSIS_VIEW, PERMISSIONS.DIAGNOSIS_CREATE, PERMISSIONS.DIAGNOSIS_UPDATE,
    PERMISSIONS.TREATMENT_VIEW_PLANS, PERMISSIONS.TREATMENT_CREATE_PLANS, PERMISSIONS.TREATMENT_UPDATE_PLANS,
    PERMISSIONS.PRESCRIPTION_VIEW, PERMISSIONS.PRESCRIPTION_CREATE, PERMISSIONS.PRESCRIPTION_UPDATE_DRAFT,
    PERMISSIONS.PRESCRIPTION_APPROVE,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_CALL_NEXT, PERMISSIONS.QUEUE_SKIP, PERMISSIONS.QUEUE_RECALL, PERMISSIONS.QUEUE_COMPLETE, PERMISSIONS.QUEUE_WAIT_TIME,
    PERMISSIONS.APPOINTMENT_CONFIRM_CANCEL,
    PERMISSIONS.LAB_VIEW_ORDERS, PERMISSIONS.LAB_CREATE_ORDERS, PERMISSIONS.LAB_VIEW_RESULTS,
    PERMISSIONS.LAB_APPROVE_RESULTS,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_ASSIGN, PERMISSIONS.BED_TRANSFER, PERMISSIONS.BED_DISCHARGE,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_STATS, PERMISSIONS.QUEUE_WAIT_TIME,
    PERMISSIONS.EMERGENCY_ACCESS,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_CREATE,
    PERMISSIONS.SCHEDULE_UPDATE,
    PERMISSIONS.SCHEDULE_DELETE,
    PERMISSIONS.SCHEDULE_MANAGE,
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_ADMIT, PERMISSIONS.PATIENT_DISCHARGE,
    PERMISSIONS.MEDICAL_VIEW_RECORDS, PERMISSIONS.MEDICAL_CREATE_RECORDS, PERMISSIONS.MEDICAL_UPDATE_RECORDS,
    PERMISSIONS.CONSULTATION_VIEW, PERMISSIONS.CONSULTATION_CREATE, PERMISSIONS.CONSULTATION_UPDATE,
    PERMISSIONS.DIAGNOSIS_VIEW, PERMISSIONS.DIAGNOSIS_CREATE, PERMISSIONS.DIAGNOSIS_UPDATE,
    PERMISSIONS.TREATMENT_VIEW_PLANS, PERMISSIONS.TREATMENT_CREATE_PLANS, PERMISSIONS.TREATMENT_UPDATE_PLANS,
    PERMISSIONS.PRESCRIPTION_VIEW, PERMISSIONS.PRESCRIPTION_CREATE, PERMISSIONS.PRESCRIPTION_UPDATE_DRAFT,
    PERMISSIONS.PRESCRIPTION_APPROVE,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.LAB_VIEW_ORDERS, PERMISSIONS.LAB_CREATE_ORDERS, PERMISSIONS.LAB_VIEW_RESULTS,
    PERMISSIONS.LAB_CREATE_RESULTS, PERMISSIONS.LAB_APPROVE_RESULTS,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_ASSIGN, PERMISSIONS.BED_TRANSFER, PERMISSIONS.BED_DISCHARGE, PERMISSIONS.BED_VIEW_STATS,
    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.EMERGENCY_ACCESS,
    PERMISSIONS.SCHEDULE_VIEW,
  ],

  [ROLES.NURSE]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.MEDICAL_VIEW_RECORDS, PERMISSIONS.MEDICAL_UPDATE_RECORDS,
    PERMISSIONS.CONSULTATION_VIEW, PERMISSIONS.CONSULTATION_UPDATE,
    PERMISSIONS.DIAGNOSIS_VIEW,
    PERMISSIONS.TREATMENT_VIEW_PLANS, PERMISSIONS.TREATMENT_UPDATE_PLANS,
    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.LAB_VIEW_ORDERS, PERMISSIONS.LAB_VIEW_RESULTS, PERMISSIONS.LAB_CREATE_RESULTS,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_SKIP, PERMISSIONS.QUEUE_WAIT_TIME,
    PERMISSIONS.EMERGENCY_ACCESS,
  ],

  [ROLES.PHARMACIST]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.PRESCRIPTION_VIEW, PERMISSIONS.PRESCRIPTION_DISPENSE,
    PERMISSIONS.PRESCRIPTION_CANCEL,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_UPDATE, PERMISSIONS.INVENTORY_MANAGE_MEDICATION,
  ],

  [ROLES.LAB_TECHNICIAN]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.LAB_VIEW_ORDERS, PERMISSIONS.LAB_UPDATE_ORDERS,
    PERMISSIONS.LAB_VIEW_RESULTS, PERMISSIONS.LAB_CREATE_RESULTS, PERMISSIONS.LAB_UPDATE_RESULTS,
  ],

  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.AUTH_REGISTER_PATIENT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE_ADMINISTRATIVE,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CONFIRM_CANCEL,
    PERMISSIONS.QUEUE_VIEW, PERMISSIONS.QUEUE_ADD, PERMISSIONS.QUEUE_WALK_IN, PERMISSIONS.QUEUE_WAIT_TIME,
    PERMISSIONS.BILL_VIEW,
  ],

  [ROLES.BILLING_STAFF]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.BILL_VIEW, PERMISSIONS.BILL_CREATE, PERMISSIONS.BILL_UPDATE,
    PERMISSIONS.BILL_PROCESS_PAYMENTS, PERMISSIONS.BILL_APPROVE_REFUND,
    PERMISSIONS.BILL_VIEW_REPORTS,
  ],

  [ROLES.PATIENT]: [
    PERMISSIONS.AUTH_LOGIN, PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.MEDICAL_VIEW_RECORDS,
    PERMISSIONS.CONSULTATION_VIEW,
    PERMISSIONS.DIAGNOSIS_VIEW,
    PERMISSIONS.PRESCRIPTION_VIEW,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_REQUEST_CANCEL,
    PERMISSIONS.BILL_VIEW,
    PERMISSIONS.LAB_VIEW_RESULTS,
    PERMISSIONS.NOTIFICATION_VIEW,
  ],

  [ROLES.GUEST]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_SELF_REGISTER,
  ],
});

// ===== PHÂN CẤP VAI TRÒ (HIERARCHY) =====
const ROLE_HIERARCHY = [
  ROLES.SUPER_ADMIN,
  ROLES.SYSTEM_ADMIN,
  ROLES.CLINICAL_ADMIN,
  ROLES.HOSPITAL_ADMIN,
  ROLES.DEPARTMENT_HEAD,
  ROLES.DOCTOR,
  ROLES.PHARMACIST,
  ROLES.NURSE,
  ROLES.LAB_TECHNICIAN,
  ROLES.BILLING_STAFF,
  ROLES.RECEPTIONIST,
  ROLES.PATIENT,
  ROLES.GUEST,
];

const ROLE_WEIGHTS = Object.freeze({
  [ROLES.SUPER_ADMIN]: 0,
  [ROLES.SYSTEM_ADMIN]: 1,
  [ROLES.CLINICAL_ADMIN]: 2,
  [ROLES.HOSPITAL_ADMIN]: 3,
  [ROLES.DEPARTMENT_HEAD]: 4,
  [ROLES.DOCTOR]: 5,
  [ROLES.PHARMACIST]: 6,
  [ROLES.NURSE]: 7,
  [ROLES.LAB_TECHNICIAN]: 8,
  [ROLES.BILLING_STAFF]: 9,
  [ROLES.RECEPTIONIST]: 10,
  [ROLES.PATIENT]: 11,
  [ROLES.GUEST]: 12,
});

// ===== CÁC HÀM HỖ TRỢ KIỂM TRA QUYỀN =====
function hasPermission(role, permission) {
  if (!role || !permission) {
    console.warn('❌ [RBAC] Thiếu role hoặc permission:', { role, permission });
    return false;
  }
  const permissions = ROLE_PERMISSIONS[role];
  if (!permissions) {
    console.warn('❌ [RBAC] Không tìm thấy vai trò:', role);
    return false;
  }
  return permissions.includes(permission);
}

function canCreateRole(currentRole, targetRole) {
  if (!currentRole || !targetRole) return false;
  if (currentRole === ROLES.SUPER_ADMIN) return targetRole !== ROLES.SUPER_ADMIN;
  const currentWeight = ROLE_WEIGHTS[currentRole];
  const targetWeight = ROLE_WEIGHTS[targetRole];
  return currentWeight !== undefined && targetWeight !== undefined && targetWeight > currentWeight;
}

function canAccessPatientData(userRole, patientId, accessorId, isEmergency = false) {
  if (isEmergency && hasPermission(userRole, PERMISSIONS.EMERGENCY_ACCESS)) {
    return true;
  }
  if (userRole === ROLES.PATIENT) {
    return patientId === accessorId;
  }
  const medicalStaff = [ROLES.DOCTOR, ROLES.NURSE, ROLES.DEPARTMENT_HEAD, ROLES.HOSPITAL_ADMIN, ROLES.CLINICAL_ADMIN, ROLES.SUPER_ADMIN];
  if (medicalStaff.includes(userRole)) {
    return hasPermission(userRole, PERMISSIONS.MEDICAL_VIEW_RECORDS);
  }
  if ([ROLES.RECEPTIONIST, ROLES.BILLING_STAFF].includes(userRole)) {
    return hasPermission(userRole, PERMISSIONS.PATIENT_VIEW);
  }
  return false;
}

function getCreatableRoles(currentRole) {
  return ROLE_HIERARCHY.filter(target => canCreateRole(currentRole, target));
}

function hasModuleAccess(role, module) {
  const modulePermissions = Object.values(PERMISSIONS).filter(p => p.startsWith(`${module}.`));
  return modulePermissions.some(perm => hasPermission(role, perm));
}

function getRolePermissions(role) {
  return ROLE_PERMISSIONS[role] || [];
}

function canManageUser(currentRole, targetRole) {
  return canCreateRole(currentRole, targetRole);
}

function getPermissionsByGroup() {
  const groups = {};
  Object.values(PERMISSIONS).forEach(permission => {
    const [group] = permission.split('.');
    if (!groups[group]) groups[group] = [];
    groups[group].push(permission);
  });
  return groups;
}

// ===== EXPORT =====
module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  ROLE_HIERARCHY,
  ROLE_WEIGHTS,
  hasPermission,
  canCreateRole,
  canAccessPatientData,
  getCreatableRoles,
  hasModuleAccess,
  getRolePermissions,
  canManageUser,
  getPermissionsByGroup,
};

// ===== DEBUG KHI CHẠY TRỰC TIẾP FILE =====
if (require.main === module) {
  console.log('=== KIỂM TRA HỆ THỐNG RBAC ===\n');
  const testCases = [
    { current: ROLES.SUPER_ADMIN, target: ROLES.DOCTOR, expected: true },
    { current: ROLES.SUPER_ADMIN, target: ROLES.HOSPITAL_ADMIN, expected: true },
    { current: ROLES.SUPER_ADMIN, target: ROLES.SUPER_ADMIN, expected: false },
    { current: ROLES.HOSPITAL_ADMIN, target: ROLES.DOCTOR, expected: true },
    { current: ROLES.HOSPITAL_ADMIN, target: ROLES.DEPARTMENT_HEAD, expected: true },
    { current: ROLES.HOSPITAL_ADMIN, target: ROLES.HOSPITAL_ADMIN, expected: false },
    { current: ROLES.DEPARTMENT_HEAD, target: ROLES.DOCTOR, expected: true },
    { current: ROLES.DOCTOR, target: ROLES.NURSE, expected: false },
  ];
  testCases.forEach((test, i) => {
    const result = canCreateRole(test.current, test.target);
    const status = result === test.expected ? '✅' : '❌';
    console.log(`${status} Test ${i + 1}: ${test.current} có thể tạo ${test.target} → ${result}`);
  });
}